/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package util.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-10-23")
public class CRDTOperation implements org.apache.thrift.TBase<CRDTOperation, CRDTOperation._Fields>, java.io.Serializable, Cloneable, Comparable<CRDTOperation> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CRDTOperation");

  private static final org.apache.thrift.protocol.TField TABLE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("tableName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PRIMARY_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("primaryKey", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField UNIQUE_PK_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("uniquePkValue", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField OP_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("opType", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField PK_WHERE_CLAUSE_FIELD_DESC = new org.apache.thrift.protocol.TField("pkWhereClause", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField NEW_FIELD_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("newFieldValues", org.apache.thrift.protocol.TType.MAP, (short)6);
  private static final org.apache.thrift.protocol.TField OLD_FIELD_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("oldFieldValues", org.apache.thrift.protocol.TType.MAP, (short)7);
  private static final org.apache.thrift.protocol.TField PARENTS_MAP_FIELD_DESC = new org.apache.thrift.protocol.TField("parentsMap", org.apache.thrift.protocol.TType.MAP, (short)8);
  private static final org.apache.thrift.protocol.TField OP_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("opId", org.apache.thrift.protocol.TType.I32, (short)9);
  private static final org.apache.thrift.protocol.TField SYMBOL_FIELD_MAP_FIELD_DESC = new org.apache.thrift.protocol.TField("symbolFieldMap", org.apache.thrift.protocol.TType.MAP, (short)10);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CRDTOperationStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CRDTOperationTupleSchemeFactory());
  }

  public String tableName; // required
  public String primaryKey; // required
  public String uniquePkValue; // required
  /**
   * 
   * @see CRDTOperationType
   */
  public CRDTOperationType opType; // required
  public String pkWhereClause; // optional
  public Map<String,String> newFieldValues; // optional
  public Map<String,String> oldFieldValues; // optional
  public Map<String,String> parentsMap; // optional
  public int opId; // required
  public Map<String,String> symbolFieldMap; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TABLE_NAME((short)1, "tableName"),
    PRIMARY_KEY((short)2, "primaryKey"),
    UNIQUE_PK_VALUE((short)3, "uniquePkValue"),
    /**
     * 
     * @see CRDTOperationType
     */
    OP_TYPE((short)4, "opType"),
    PK_WHERE_CLAUSE((short)5, "pkWhereClause"),
    NEW_FIELD_VALUES((short)6, "newFieldValues"),
    OLD_FIELD_VALUES((short)7, "oldFieldValues"),
    PARENTS_MAP((short)8, "parentsMap"),
    OP_ID((short)9, "opId"),
    SYMBOL_FIELD_MAP((short)10, "symbolFieldMap");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TABLE_NAME
          return TABLE_NAME;
        case 2: // PRIMARY_KEY
          return PRIMARY_KEY;
        case 3: // UNIQUE_PK_VALUE
          return UNIQUE_PK_VALUE;
        case 4: // OP_TYPE
          return OP_TYPE;
        case 5: // PK_WHERE_CLAUSE
          return PK_WHERE_CLAUSE;
        case 6: // NEW_FIELD_VALUES
          return NEW_FIELD_VALUES;
        case 7: // OLD_FIELD_VALUES
          return OLD_FIELD_VALUES;
        case 8: // PARENTS_MAP
          return PARENTS_MAP;
        case 9: // OP_ID
          return OP_ID;
        case 10: // SYMBOL_FIELD_MAP
          return SYMBOL_FIELD_MAP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __OPID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.PK_WHERE_CLAUSE,_Fields.NEW_FIELD_VALUES,_Fields.OLD_FIELD_VALUES,_Fields.PARENTS_MAP,_Fields.SYMBOL_FIELD_MAP};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TABLE_NAME, new org.apache.thrift.meta_data.FieldMetaData("tableName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PRIMARY_KEY, new org.apache.thrift.meta_data.FieldMetaData("primaryKey", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.UNIQUE_PK_VALUE, new org.apache.thrift.meta_data.FieldMetaData("uniquePkValue", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OP_TYPE, new org.apache.thrift.meta_data.FieldMetaData("opType", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, CRDTOperationType.class)));
    tmpMap.put(_Fields.PK_WHERE_CLAUSE, new org.apache.thrift.meta_data.FieldMetaData("pkWhereClause", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NEW_FIELD_VALUES, new org.apache.thrift.meta_data.FieldMetaData("newFieldValues", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.OLD_FIELD_VALUES, new org.apache.thrift.meta_data.FieldMetaData("oldFieldValues", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.PARENTS_MAP, new org.apache.thrift.meta_data.FieldMetaData("parentsMap", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.OP_ID, new org.apache.thrift.meta_data.FieldMetaData("opId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SYMBOL_FIELD_MAP, new org.apache.thrift.meta_data.FieldMetaData("symbolFieldMap", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CRDTOperation.class, metaDataMap);
  }

  public CRDTOperation() {
  }

  public CRDTOperation(
    String tableName,
    String primaryKey,
    String uniquePkValue,
    CRDTOperationType opType,
    int opId)
  {
    this();
    this.tableName = tableName;
    this.primaryKey = primaryKey;
    this.uniquePkValue = uniquePkValue;
    this.opType = opType;
    this.opId = opId;
    setOpIdIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CRDTOperation(CRDTOperation other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetTableName()) {
      this.tableName = other.tableName;
    }
    if (other.isSetPrimaryKey()) {
      this.primaryKey = other.primaryKey;
    }
    if (other.isSetUniquePkValue()) {
      this.uniquePkValue = other.uniquePkValue;
    }
    if (other.isSetOpType()) {
      this.opType = other.opType;
    }
    if (other.isSetPkWhereClause()) {
      this.pkWhereClause = other.pkWhereClause;
    }
    if (other.isSetNewFieldValues()) {
      Map<String,String> __this__newFieldValues = new HashMap<String,String>(other.newFieldValues);
      this.newFieldValues = __this__newFieldValues;
    }
    if (other.isSetOldFieldValues()) {
      Map<String,String> __this__oldFieldValues = new HashMap<String,String>(other.oldFieldValues);
      this.oldFieldValues = __this__oldFieldValues;
    }
    if (other.isSetParentsMap()) {
      Map<String,String> __this__parentsMap = new HashMap<String,String>(other.parentsMap);
      this.parentsMap = __this__parentsMap;
    }
    this.opId = other.opId;
    if (other.isSetSymbolFieldMap()) {
      Map<String,String> __this__symbolFieldMap = new HashMap<String,String>(other.symbolFieldMap);
      this.symbolFieldMap = __this__symbolFieldMap;
    }
  }

  public CRDTOperation deepCopy() {
    return new CRDTOperation(this);
  }

  @Override
  public void clear() {
    this.tableName = null;
    this.primaryKey = null;
    this.uniquePkValue = null;
    this.opType = null;
    this.pkWhereClause = null;
    this.newFieldValues = null;
    this.oldFieldValues = null;
    this.parentsMap = null;
    setOpIdIsSet(false);
    this.opId = 0;
    this.symbolFieldMap = null;
  }

  public String getTableName() {
    return this.tableName;
  }

  public CRDTOperation setTableName(String tableName) {
    this.tableName = tableName;
    return this;
  }

  public void unsetTableName() {
    this.tableName = null;
  }

  /** Returns true if field tableName is set (has been assigned a value) and false otherwise */
  public boolean isSetTableName() {
    return this.tableName != null;
  }

  public void setTableNameIsSet(boolean value) {
    if (!value) {
      this.tableName = null;
    }
  }

  public String getPrimaryKey() {
    return this.primaryKey;
  }

  public CRDTOperation setPrimaryKey(String primaryKey) {
    this.primaryKey = primaryKey;
    return this;
  }

  public void unsetPrimaryKey() {
    this.primaryKey = null;
  }

  /** Returns true if field primaryKey is set (has been assigned a value) and false otherwise */
  public boolean isSetPrimaryKey() {
    return this.primaryKey != null;
  }

  public void setPrimaryKeyIsSet(boolean value) {
    if (!value) {
      this.primaryKey = null;
    }
  }

  public String getUniquePkValue() {
    return this.uniquePkValue;
  }

  public CRDTOperation setUniquePkValue(String uniquePkValue) {
    this.uniquePkValue = uniquePkValue;
    return this;
  }

  public void unsetUniquePkValue() {
    this.uniquePkValue = null;
  }

  /** Returns true if field uniquePkValue is set (has been assigned a value) and false otherwise */
  public boolean isSetUniquePkValue() {
    return this.uniquePkValue != null;
  }

  public void setUniquePkValueIsSet(boolean value) {
    if (!value) {
      this.uniquePkValue = null;
    }
  }

  /**
   * 
   * @see CRDTOperationType
   */
  public CRDTOperationType getOpType() {
    return this.opType;
  }

  /**
   * 
   * @see CRDTOperationType
   */
  public CRDTOperation setOpType(CRDTOperationType opType) {
    this.opType = opType;
    return this;
  }

  public void unsetOpType() {
    this.opType = null;
  }

  /** Returns true if field opType is set (has been assigned a value) and false otherwise */
  public boolean isSetOpType() {
    return this.opType != null;
  }

  public void setOpTypeIsSet(boolean value) {
    if (!value) {
      this.opType = null;
    }
  }

  public String getPkWhereClause() {
    return this.pkWhereClause;
  }

  public CRDTOperation setPkWhereClause(String pkWhereClause) {
    this.pkWhereClause = pkWhereClause;
    return this;
  }

  public void unsetPkWhereClause() {
    this.pkWhereClause = null;
  }

  /** Returns true if field pkWhereClause is set (has been assigned a value) and false otherwise */
  public boolean isSetPkWhereClause() {
    return this.pkWhereClause != null;
  }

  public void setPkWhereClauseIsSet(boolean value) {
    if (!value) {
      this.pkWhereClause = null;
    }
  }

  public int getNewFieldValuesSize() {
    return (this.newFieldValues == null) ? 0 : this.newFieldValues.size();
  }

  public void putToNewFieldValues(String key, String val) {
    if (this.newFieldValues == null) {
      this.newFieldValues = new HashMap<String,String>();
    }
    this.newFieldValues.put(key, val);
  }

  public Map<String,String> getNewFieldValues() {
    return this.newFieldValues;
  }

  public CRDTOperation setNewFieldValues(Map<String,String> newFieldValues) {
    this.newFieldValues = newFieldValues;
    return this;
  }

  public void unsetNewFieldValues() {
    this.newFieldValues = null;
  }

  /** Returns true if field newFieldValues is set (has been assigned a value) and false otherwise */
  public boolean isSetNewFieldValues() {
    return this.newFieldValues != null;
  }

  public void setNewFieldValuesIsSet(boolean value) {
    if (!value) {
      this.newFieldValues = null;
    }
  }

  public int getOldFieldValuesSize() {
    return (this.oldFieldValues == null) ? 0 : this.oldFieldValues.size();
  }

  public void putToOldFieldValues(String key, String val) {
    if (this.oldFieldValues == null) {
      this.oldFieldValues = new HashMap<String,String>();
    }
    this.oldFieldValues.put(key, val);
  }

  public Map<String,String> getOldFieldValues() {
    return this.oldFieldValues;
  }

  public CRDTOperation setOldFieldValues(Map<String,String> oldFieldValues) {
    this.oldFieldValues = oldFieldValues;
    return this;
  }

  public void unsetOldFieldValues() {
    this.oldFieldValues = null;
  }

  /** Returns true if field oldFieldValues is set (has been assigned a value) and false otherwise */
  public boolean isSetOldFieldValues() {
    return this.oldFieldValues != null;
  }

  public void setOldFieldValuesIsSet(boolean value) {
    if (!value) {
      this.oldFieldValues = null;
    }
  }

  public int getParentsMapSize() {
    return (this.parentsMap == null) ? 0 : this.parentsMap.size();
  }

  public void putToParentsMap(String key, String val) {
    if (this.parentsMap == null) {
      this.parentsMap = new HashMap<String,String>();
    }
    this.parentsMap.put(key, val);
  }

  public Map<String,String> getParentsMap() {
    return this.parentsMap;
  }

  public CRDTOperation setParentsMap(Map<String,String> parentsMap) {
    this.parentsMap = parentsMap;
    return this;
  }

  public void unsetParentsMap() {
    this.parentsMap = null;
  }

  /** Returns true if field parentsMap is set (has been assigned a value) and false otherwise */
  public boolean isSetParentsMap() {
    return this.parentsMap != null;
  }

  public void setParentsMapIsSet(boolean value) {
    if (!value) {
      this.parentsMap = null;
    }
  }

  public int getOpId() {
    return this.opId;
  }

  public CRDTOperation setOpId(int opId) {
    this.opId = opId;
    setOpIdIsSet(true);
    return this;
  }

  public void unsetOpId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __OPID_ISSET_ID);
  }

  /** Returns true if field opId is set (has been assigned a value) and false otherwise */
  public boolean isSetOpId() {
    return EncodingUtils.testBit(__isset_bitfield, __OPID_ISSET_ID);
  }

  public void setOpIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __OPID_ISSET_ID, value);
  }

  public int getSymbolFieldMapSize() {
    return (this.symbolFieldMap == null) ? 0 : this.symbolFieldMap.size();
  }

  public void putToSymbolFieldMap(String key, String val) {
    if (this.symbolFieldMap == null) {
      this.symbolFieldMap = new HashMap<String,String>();
    }
    this.symbolFieldMap.put(key, val);
  }

  public Map<String,String> getSymbolFieldMap() {
    return this.symbolFieldMap;
  }

  public CRDTOperation setSymbolFieldMap(Map<String,String> symbolFieldMap) {
    this.symbolFieldMap = symbolFieldMap;
    return this;
  }

  public void unsetSymbolFieldMap() {
    this.symbolFieldMap = null;
  }

  /** Returns true if field symbolFieldMap is set (has been assigned a value) and false otherwise */
  public boolean isSetSymbolFieldMap() {
    return this.symbolFieldMap != null;
  }

  public void setSymbolFieldMapIsSet(boolean value) {
    if (!value) {
      this.symbolFieldMap = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TABLE_NAME:
      if (value == null) {
        unsetTableName();
      } else {
        setTableName((String)value);
      }
      break;

    case PRIMARY_KEY:
      if (value == null) {
        unsetPrimaryKey();
      } else {
        setPrimaryKey((String)value);
      }
      break;

    case UNIQUE_PK_VALUE:
      if (value == null) {
        unsetUniquePkValue();
      } else {
        setUniquePkValue((String)value);
      }
      break;

    case OP_TYPE:
      if (value == null) {
        unsetOpType();
      } else {
        setOpType((CRDTOperationType)value);
      }
      break;

    case PK_WHERE_CLAUSE:
      if (value == null) {
        unsetPkWhereClause();
      } else {
        setPkWhereClause((String)value);
      }
      break;

    case NEW_FIELD_VALUES:
      if (value == null) {
        unsetNewFieldValues();
      } else {
        setNewFieldValues((Map<String,String>)value);
      }
      break;

    case OLD_FIELD_VALUES:
      if (value == null) {
        unsetOldFieldValues();
      } else {
        setOldFieldValues((Map<String,String>)value);
      }
      break;

    case PARENTS_MAP:
      if (value == null) {
        unsetParentsMap();
      } else {
        setParentsMap((Map<String,String>)value);
      }
      break;

    case OP_ID:
      if (value == null) {
        unsetOpId();
      } else {
        setOpId((Integer)value);
      }
      break;

    case SYMBOL_FIELD_MAP:
      if (value == null) {
        unsetSymbolFieldMap();
      } else {
        setSymbolFieldMap((Map<String,String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TABLE_NAME:
      return getTableName();

    case PRIMARY_KEY:
      return getPrimaryKey();

    case UNIQUE_PK_VALUE:
      return getUniquePkValue();

    case OP_TYPE:
      return getOpType();

    case PK_WHERE_CLAUSE:
      return getPkWhereClause();

    case NEW_FIELD_VALUES:
      return getNewFieldValues();

    case OLD_FIELD_VALUES:
      return getOldFieldValues();

    case PARENTS_MAP:
      return getParentsMap();

    case OP_ID:
      return Integer.valueOf(getOpId());

    case SYMBOL_FIELD_MAP:
      return getSymbolFieldMap();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TABLE_NAME:
      return isSetTableName();
    case PRIMARY_KEY:
      return isSetPrimaryKey();
    case UNIQUE_PK_VALUE:
      return isSetUniquePkValue();
    case OP_TYPE:
      return isSetOpType();
    case PK_WHERE_CLAUSE:
      return isSetPkWhereClause();
    case NEW_FIELD_VALUES:
      return isSetNewFieldValues();
    case OLD_FIELD_VALUES:
      return isSetOldFieldValues();
    case PARENTS_MAP:
      return isSetParentsMap();
    case OP_ID:
      return isSetOpId();
    case SYMBOL_FIELD_MAP:
      return isSetSymbolFieldMap();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CRDTOperation)
      return this.equals((CRDTOperation)that);
    return false;
  }

  public boolean equals(CRDTOperation that) {
    if (that == null)
      return false;

    boolean this_present_tableName = true && this.isSetTableName();
    boolean that_present_tableName = true && that.isSetTableName();
    if (this_present_tableName || that_present_tableName) {
      if (!(this_present_tableName && that_present_tableName))
        return false;
      if (!this.tableName.equals(that.tableName))
        return false;
    }

    boolean this_present_primaryKey = true && this.isSetPrimaryKey();
    boolean that_present_primaryKey = true && that.isSetPrimaryKey();
    if (this_present_primaryKey || that_present_primaryKey) {
      if (!(this_present_primaryKey && that_present_primaryKey))
        return false;
      if (!this.primaryKey.equals(that.primaryKey))
        return false;
    }

    boolean this_present_uniquePkValue = true && this.isSetUniquePkValue();
    boolean that_present_uniquePkValue = true && that.isSetUniquePkValue();
    if (this_present_uniquePkValue || that_present_uniquePkValue) {
      if (!(this_present_uniquePkValue && that_present_uniquePkValue))
        return false;
      if (!this.uniquePkValue.equals(that.uniquePkValue))
        return false;
    }

    boolean this_present_opType = true && this.isSetOpType();
    boolean that_present_opType = true && that.isSetOpType();
    if (this_present_opType || that_present_opType) {
      if (!(this_present_opType && that_present_opType))
        return false;
      if (!this.opType.equals(that.opType))
        return false;
    }

    boolean this_present_pkWhereClause = true && this.isSetPkWhereClause();
    boolean that_present_pkWhereClause = true && that.isSetPkWhereClause();
    if (this_present_pkWhereClause || that_present_pkWhereClause) {
      if (!(this_present_pkWhereClause && that_present_pkWhereClause))
        return false;
      if (!this.pkWhereClause.equals(that.pkWhereClause))
        return false;
    }

    boolean this_present_newFieldValues = true && this.isSetNewFieldValues();
    boolean that_present_newFieldValues = true && that.isSetNewFieldValues();
    if (this_present_newFieldValues || that_present_newFieldValues) {
      if (!(this_present_newFieldValues && that_present_newFieldValues))
        return false;
      if (!this.newFieldValues.equals(that.newFieldValues))
        return false;
    }

    boolean this_present_oldFieldValues = true && this.isSetOldFieldValues();
    boolean that_present_oldFieldValues = true && that.isSetOldFieldValues();
    if (this_present_oldFieldValues || that_present_oldFieldValues) {
      if (!(this_present_oldFieldValues && that_present_oldFieldValues))
        return false;
      if (!this.oldFieldValues.equals(that.oldFieldValues))
        return false;
    }

    boolean this_present_parentsMap = true && this.isSetParentsMap();
    boolean that_present_parentsMap = true && that.isSetParentsMap();
    if (this_present_parentsMap || that_present_parentsMap) {
      if (!(this_present_parentsMap && that_present_parentsMap))
        return false;
      if (!this.parentsMap.equals(that.parentsMap))
        return false;
    }

    boolean this_present_opId = true;
    boolean that_present_opId = true;
    if (this_present_opId || that_present_opId) {
      if (!(this_present_opId && that_present_opId))
        return false;
      if (this.opId != that.opId)
        return false;
    }

    boolean this_present_symbolFieldMap = true && this.isSetSymbolFieldMap();
    boolean that_present_symbolFieldMap = true && that.isSetSymbolFieldMap();
    if (this_present_symbolFieldMap || that_present_symbolFieldMap) {
      if (!(this_present_symbolFieldMap && that_present_symbolFieldMap))
        return false;
      if (!this.symbolFieldMap.equals(that.symbolFieldMap))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_tableName = true && (isSetTableName());
    list.add(present_tableName);
    if (present_tableName)
      list.add(tableName);

    boolean present_primaryKey = true && (isSetPrimaryKey());
    list.add(present_primaryKey);
    if (present_primaryKey)
      list.add(primaryKey);

    boolean present_uniquePkValue = true && (isSetUniquePkValue());
    list.add(present_uniquePkValue);
    if (present_uniquePkValue)
      list.add(uniquePkValue);

    boolean present_opType = true && (isSetOpType());
    list.add(present_opType);
    if (present_opType)
      list.add(opType.getValue());

    boolean present_pkWhereClause = true && (isSetPkWhereClause());
    list.add(present_pkWhereClause);
    if (present_pkWhereClause)
      list.add(pkWhereClause);

    boolean present_newFieldValues = true && (isSetNewFieldValues());
    list.add(present_newFieldValues);
    if (present_newFieldValues)
      list.add(newFieldValues);

    boolean present_oldFieldValues = true && (isSetOldFieldValues());
    list.add(present_oldFieldValues);
    if (present_oldFieldValues)
      list.add(oldFieldValues);

    boolean present_parentsMap = true && (isSetParentsMap());
    list.add(present_parentsMap);
    if (present_parentsMap)
      list.add(parentsMap);

    boolean present_opId = true;
    list.add(present_opId);
    if (present_opId)
      list.add(opId);

    boolean present_symbolFieldMap = true && (isSetSymbolFieldMap());
    list.add(present_symbolFieldMap);
    if (present_symbolFieldMap)
      list.add(symbolFieldMap);

    return list.hashCode();
  }

  @Override
  public int compareTo(CRDTOperation other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTableName()).compareTo(other.isSetTableName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTableName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tableName, other.tableName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPrimaryKey()).compareTo(other.isSetPrimaryKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrimaryKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.primaryKey, other.primaryKey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUniquePkValue()).compareTo(other.isSetUniquePkValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUniquePkValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.uniquePkValue, other.uniquePkValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOpType()).compareTo(other.isSetOpType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOpType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.opType, other.opType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPkWhereClause()).compareTo(other.isSetPkWhereClause());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPkWhereClause()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pkWhereClause, other.pkWhereClause);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNewFieldValues()).compareTo(other.isSetNewFieldValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNewFieldValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.newFieldValues, other.newFieldValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOldFieldValues()).compareTo(other.isSetOldFieldValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOldFieldValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.oldFieldValues, other.oldFieldValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetParentsMap()).compareTo(other.isSetParentsMap());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParentsMap()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.parentsMap, other.parentsMap);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOpId()).compareTo(other.isSetOpId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOpId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.opId, other.opId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSymbolFieldMap()).compareTo(other.isSetSymbolFieldMap());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSymbolFieldMap()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.symbolFieldMap, other.symbolFieldMap);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CRDTOperation(");
    boolean first = true;

    sb.append("tableName:");
    if (this.tableName == null) {
      sb.append("null");
    } else {
      sb.append(this.tableName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("primaryKey:");
    if (this.primaryKey == null) {
      sb.append("null");
    } else {
      sb.append(this.primaryKey);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("uniquePkValue:");
    if (this.uniquePkValue == null) {
      sb.append("null");
    } else {
      sb.append(this.uniquePkValue);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("opType:");
    if (this.opType == null) {
      sb.append("null");
    } else {
      sb.append(this.opType);
    }
    first = false;
    if (isSetPkWhereClause()) {
      if (!first) sb.append(", ");
      sb.append("pkWhereClause:");
      if (this.pkWhereClause == null) {
        sb.append("null");
      } else {
        sb.append(this.pkWhereClause);
      }
      first = false;
    }
    if (isSetNewFieldValues()) {
      if (!first) sb.append(", ");
      sb.append("newFieldValues:");
      if (this.newFieldValues == null) {
        sb.append("null");
      } else {
        sb.append(this.newFieldValues);
      }
      first = false;
    }
    if (isSetOldFieldValues()) {
      if (!first) sb.append(", ");
      sb.append("oldFieldValues:");
      if (this.oldFieldValues == null) {
        sb.append("null");
      } else {
        sb.append(this.oldFieldValues);
      }
      first = false;
    }
    if (isSetParentsMap()) {
      if (!first) sb.append(", ");
      sb.append("parentsMap:");
      if (this.parentsMap == null) {
        sb.append("null");
      } else {
        sb.append(this.parentsMap);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("opId:");
    sb.append(this.opId);
    first = false;
    if (isSetSymbolFieldMap()) {
      if (!first) sb.append(", ");
      sb.append("symbolFieldMap:");
      if (this.symbolFieldMap == null) {
        sb.append("null");
      } else {
        sb.append(this.symbolFieldMap);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (tableName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'tableName' was not present! Struct: " + toString());
    }
    if (primaryKey == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'primaryKey' was not present! Struct: " + toString());
    }
    if (uniquePkValue == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'uniquePkValue' was not present! Struct: " + toString());
    }
    if (opType == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'opType' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'opId' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CRDTOperationStandardSchemeFactory implements SchemeFactory {
    public CRDTOperationStandardScheme getScheme() {
      return new CRDTOperationStandardScheme();
    }
  }

  private static class CRDTOperationStandardScheme extends StandardScheme<CRDTOperation> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CRDTOperation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TABLE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.tableName = iprot.readString();
              struct.setTableNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PRIMARY_KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.primaryKey = iprot.readString();
              struct.setPrimaryKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // UNIQUE_PK_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.uniquePkValue = iprot.readString();
              struct.setUniquePkValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // OP_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.opType = util.thrift.CRDTOperationType.findByValue(iprot.readI32());
              struct.setOpTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // PK_WHERE_CLAUSE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.pkWhereClause = iprot.readString();
              struct.setPkWhereClauseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // NEW_FIELD_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map32 = iprot.readMapBegin();
                struct.newFieldValues = new HashMap<String,String>(2*_map32.size);
                String _key33;
                String _val34;
                for (int _i35 = 0; _i35 < _map32.size; ++_i35)
                {
                  _key33 = iprot.readString();
                  _val34 = iprot.readString();
                  struct.newFieldValues.put(_key33, _val34);
                }
                iprot.readMapEnd();
              }
              struct.setNewFieldValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // OLD_FIELD_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map36 = iprot.readMapBegin();
                struct.oldFieldValues = new HashMap<String,String>(2*_map36.size);
                String _key37;
                String _val38;
                for (int _i39 = 0; _i39 < _map36.size; ++_i39)
                {
                  _key37 = iprot.readString();
                  _val38 = iprot.readString();
                  struct.oldFieldValues.put(_key37, _val38);
                }
                iprot.readMapEnd();
              }
              struct.setOldFieldValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // PARENTS_MAP
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map40 = iprot.readMapBegin();
                struct.parentsMap = new HashMap<String,String>(2*_map40.size);
                String _key41;
                String _val42;
                for (int _i43 = 0; _i43 < _map40.size; ++_i43)
                {
                  _key41 = iprot.readString();
                  _val42 = iprot.readString();
                  struct.parentsMap.put(_key41, _val42);
                }
                iprot.readMapEnd();
              }
              struct.setParentsMapIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // OP_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.opId = iprot.readI32();
              struct.setOpIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // SYMBOL_FIELD_MAP
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map44 = iprot.readMapBegin();
                struct.symbolFieldMap = new HashMap<String,String>(2*_map44.size);
                String _key45;
                String _val46;
                for (int _i47 = 0; _i47 < _map44.size; ++_i47)
                {
                  _key45 = iprot.readString();
                  _val46 = iprot.readString();
                  struct.symbolFieldMap.put(_key45, _val46);
                }
                iprot.readMapEnd();
              }
              struct.setSymbolFieldMapIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetOpId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'opId' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CRDTOperation struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.tableName != null) {
        oprot.writeFieldBegin(TABLE_NAME_FIELD_DESC);
        oprot.writeString(struct.tableName);
        oprot.writeFieldEnd();
      }
      if (struct.primaryKey != null) {
        oprot.writeFieldBegin(PRIMARY_KEY_FIELD_DESC);
        oprot.writeString(struct.primaryKey);
        oprot.writeFieldEnd();
      }
      if (struct.uniquePkValue != null) {
        oprot.writeFieldBegin(UNIQUE_PK_VALUE_FIELD_DESC);
        oprot.writeString(struct.uniquePkValue);
        oprot.writeFieldEnd();
      }
      if (struct.opType != null) {
        oprot.writeFieldBegin(OP_TYPE_FIELD_DESC);
        oprot.writeI32(struct.opType.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.pkWhereClause != null) {
        if (struct.isSetPkWhereClause()) {
          oprot.writeFieldBegin(PK_WHERE_CLAUSE_FIELD_DESC);
          oprot.writeString(struct.pkWhereClause);
          oprot.writeFieldEnd();
        }
      }
      if (struct.newFieldValues != null) {
        if (struct.isSetNewFieldValues()) {
          oprot.writeFieldBegin(NEW_FIELD_VALUES_FIELD_DESC);
          {
            oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.newFieldValues.size()));
            for (Map.Entry<String, String> _iter48 : struct.newFieldValues.entrySet())
            {
              oprot.writeString(_iter48.getKey());
              oprot.writeString(_iter48.getValue());
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.oldFieldValues != null) {
        if (struct.isSetOldFieldValues()) {
          oprot.writeFieldBegin(OLD_FIELD_VALUES_FIELD_DESC);
          {
            oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.oldFieldValues.size()));
            for (Map.Entry<String, String> _iter49 : struct.oldFieldValues.entrySet())
            {
              oprot.writeString(_iter49.getKey());
              oprot.writeString(_iter49.getValue());
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.parentsMap != null) {
        if (struct.isSetParentsMap()) {
          oprot.writeFieldBegin(PARENTS_MAP_FIELD_DESC);
          {
            oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.parentsMap.size()));
            for (Map.Entry<String, String> _iter50 : struct.parentsMap.entrySet())
            {
              oprot.writeString(_iter50.getKey());
              oprot.writeString(_iter50.getValue());
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldBegin(OP_ID_FIELD_DESC);
      oprot.writeI32(struct.opId);
      oprot.writeFieldEnd();
      if (struct.symbolFieldMap != null) {
        if (struct.isSetSymbolFieldMap()) {
          oprot.writeFieldBegin(SYMBOL_FIELD_MAP_FIELD_DESC);
          {
            oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.symbolFieldMap.size()));
            for (Map.Entry<String, String> _iter51 : struct.symbolFieldMap.entrySet())
            {
              oprot.writeString(_iter51.getKey());
              oprot.writeString(_iter51.getValue());
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CRDTOperationTupleSchemeFactory implements SchemeFactory {
    public CRDTOperationTupleScheme getScheme() {
      return new CRDTOperationTupleScheme();
    }
  }

  private static class CRDTOperationTupleScheme extends TupleScheme<CRDTOperation> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CRDTOperation struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.tableName);
      oprot.writeString(struct.primaryKey);
      oprot.writeString(struct.uniquePkValue);
      oprot.writeI32(struct.opType.getValue());
      oprot.writeI32(struct.opId);
      BitSet optionals = new BitSet();
      if (struct.isSetPkWhereClause()) {
        optionals.set(0);
      }
      if (struct.isSetNewFieldValues()) {
        optionals.set(1);
      }
      if (struct.isSetOldFieldValues()) {
        optionals.set(2);
      }
      if (struct.isSetParentsMap()) {
        optionals.set(3);
      }
      if (struct.isSetSymbolFieldMap()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetPkWhereClause()) {
        oprot.writeString(struct.pkWhereClause);
      }
      if (struct.isSetNewFieldValues()) {
        {
          oprot.writeI32(struct.newFieldValues.size());
          for (Map.Entry<String, String> _iter52 : struct.newFieldValues.entrySet())
          {
            oprot.writeString(_iter52.getKey());
            oprot.writeString(_iter52.getValue());
          }
        }
      }
      if (struct.isSetOldFieldValues()) {
        {
          oprot.writeI32(struct.oldFieldValues.size());
          for (Map.Entry<String, String> _iter53 : struct.oldFieldValues.entrySet())
          {
            oprot.writeString(_iter53.getKey());
            oprot.writeString(_iter53.getValue());
          }
        }
      }
      if (struct.isSetParentsMap()) {
        {
          oprot.writeI32(struct.parentsMap.size());
          for (Map.Entry<String, String> _iter54 : struct.parentsMap.entrySet())
          {
            oprot.writeString(_iter54.getKey());
            oprot.writeString(_iter54.getValue());
          }
        }
      }
      if (struct.isSetSymbolFieldMap()) {
        {
          oprot.writeI32(struct.symbolFieldMap.size());
          for (Map.Entry<String, String> _iter55 : struct.symbolFieldMap.entrySet())
          {
            oprot.writeString(_iter55.getKey());
            oprot.writeString(_iter55.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CRDTOperation struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.tableName = iprot.readString();
      struct.setTableNameIsSet(true);
      struct.primaryKey = iprot.readString();
      struct.setPrimaryKeyIsSet(true);
      struct.uniquePkValue = iprot.readString();
      struct.setUniquePkValueIsSet(true);
      struct.opType = util.thrift.CRDTOperationType.findByValue(iprot.readI32());
      struct.setOpTypeIsSet(true);
      struct.opId = iprot.readI32();
      struct.setOpIdIsSet(true);
      BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.pkWhereClause = iprot.readString();
        struct.setPkWhereClauseIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TMap _map56 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.newFieldValues = new HashMap<String,String>(2*_map56.size);
          String _key57;
          String _val58;
          for (int _i59 = 0; _i59 < _map56.size; ++_i59)
          {
            _key57 = iprot.readString();
            _val58 = iprot.readString();
            struct.newFieldValues.put(_key57, _val58);
          }
        }
        struct.setNewFieldValuesIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TMap _map60 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.oldFieldValues = new HashMap<String,String>(2*_map60.size);
          String _key61;
          String _val62;
          for (int _i63 = 0; _i63 < _map60.size; ++_i63)
          {
            _key61 = iprot.readString();
            _val62 = iprot.readString();
            struct.oldFieldValues.put(_key61, _val62);
          }
        }
        struct.setOldFieldValuesIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TMap _map64 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.parentsMap = new HashMap<String,String>(2*_map64.size);
          String _key65;
          String _val66;
          for (int _i67 = 0; _i67 < _map64.size; ++_i67)
          {
            _key65 = iprot.readString();
            _val66 = iprot.readString();
            struct.parentsMap.put(_key65, _val66);
          }
        }
        struct.setParentsMapIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TMap _map68 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.symbolFieldMap = new HashMap<String,String>(2*_map68.size);
          String _key69;
          String _val70;
          for (int _i71 = 0; _i71 < _map68.size; ++_i71)
          {
            _key69 = iprot.readString();
            _val70 = iprot.readString();
            struct.symbolFieldMap.put(_key69, _val70);
          }
        }
        struct.setSymbolFieldMapIsSet(true);
      }
    }
  }

}

