/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package util.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class RequestUnit extends org.apache.thrift.TUnion<RequestUnit, RequestUnit._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RequestUnit");
  private static final org.apache.thrift.protocol.TField UNIQUE_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("uniqueValue", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField APPLY_DELTA_FIELD_DESC = new org.apache.thrift.protocol.TField("applyDelta", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField REQUEST_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("requestValue", org.apache.thrift.protocol.TType.STRUCT, (short)3);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    UNIQUE_VALUE((short)1, "uniqueValue"),
    APPLY_DELTA((short)2, "applyDelta"),
    REQUEST_VALUE((short)3, "requestValue");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // UNIQUE_VALUE
          return UNIQUE_VALUE;
        case 2: // APPLY_DELTA
          return APPLY_DELTA;
        case 3: // REQUEST_VALUE
          return REQUEST_VALUE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.UNIQUE_VALUE, new org.apache.thrift.meta_data.FieldMetaData("uniqueValue", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, UniqueValue.class)));
    tmpMap.put(_Fields.APPLY_DELTA, new org.apache.thrift.meta_data.FieldMetaData("applyDelta", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ApplyDelta.class)));
    tmpMap.put(_Fields.REQUEST_VALUE, new org.apache.thrift.meta_data.FieldMetaData("requestValue", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, RequestValue.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RequestUnit.class, metaDataMap);
  }

  public RequestUnit() {
    super();
  }

  public RequestUnit(_Fields setField, Object value) {
    super(setField, value);
  }

  public RequestUnit(RequestUnit other) {
    super(other);
  }
  public RequestUnit deepCopy() {
    return new RequestUnit(this);
  }

  public static RequestUnit uniqueValue(UniqueValue value) {
    RequestUnit x = new RequestUnit();
    x.setUniqueValue(value);
    return x;
  }

  public static RequestUnit applyDelta(ApplyDelta value) {
    RequestUnit x = new RequestUnit();
    x.setApplyDelta(value);
    return x;
  }

  public static RequestUnit requestValue(RequestValue value) {
    RequestUnit x = new RequestUnit();
    x.setRequestValue(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case UNIQUE_VALUE:
        if (value instanceof UniqueValue) {
          break;
        }
        throw new ClassCastException("Was expecting value of type UniqueValue for field 'uniqueValue', but got " + value.getClass().getSimpleName());
      case APPLY_DELTA:
        if (value instanceof ApplyDelta) {
          break;
        }
        throw new ClassCastException("Was expecting value of type ApplyDelta for field 'applyDelta', but got " + value.getClass().getSimpleName());
      case REQUEST_VALUE:
        if (value instanceof RequestValue) {
          break;
        }
        throw new ClassCastException("Was expecting value of type RequestValue for field 'requestValue', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case UNIQUE_VALUE:
          if (field.type == UNIQUE_VALUE_FIELD_DESC.type) {
            UniqueValue uniqueValue;
            uniqueValue = new UniqueValue();
            uniqueValue.read(iprot);
            return uniqueValue;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case APPLY_DELTA:
          if (field.type == APPLY_DELTA_FIELD_DESC.type) {
            ApplyDelta applyDelta;
            applyDelta = new ApplyDelta();
            applyDelta.read(iprot);
            return applyDelta;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case REQUEST_VALUE:
          if (field.type == REQUEST_VALUE_FIELD_DESC.type) {
            RequestValue requestValue;
            requestValue = new RequestValue();
            requestValue.read(iprot);
            return requestValue;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case UNIQUE_VALUE:
        UniqueValue uniqueValue = (UniqueValue)value_;
        uniqueValue.write(oprot);
        return;
      case APPLY_DELTA:
        ApplyDelta applyDelta = (ApplyDelta)value_;
        applyDelta.write(oprot);
        return;
      case REQUEST_VALUE:
        RequestValue requestValue = (RequestValue)value_;
        requestValue.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case UNIQUE_VALUE:
          UniqueValue uniqueValue;
          uniqueValue = new UniqueValue();
          uniqueValue.read(iprot);
          return uniqueValue;
        case APPLY_DELTA:
          ApplyDelta applyDelta;
          applyDelta = new ApplyDelta();
          applyDelta.read(iprot);
          return applyDelta;
        case REQUEST_VALUE:
          RequestValue requestValue;
          requestValue = new RequestValue();
          requestValue.read(iprot);
          return requestValue;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case UNIQUE_VALUE:
        UniqueValue uniqueValue = (UniqueValue)value_;
        uniqueValue.write(oprot);
        return;
      case APPLY_DELTA:
        ApplyDelta applyDelta = (ApplyDelta)value_;
        applyDelta.write(oprot);
        return;
      case REQUEST_VALUE:
        RequestValue requestValue = (RequestValue)value_;
        requestValue.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case UNIQUE_VALUE:
        return UNIQUE_VALUE_FIELD_DESC;
      case APPLY_DELTA:
        return APPLY_DELTA_FIELD_DESC;
      case REQUEST_VALUE:
        return REQUEST_VALUE_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public UniqueValue getUniqueValue() {
    if (getSetField() == _Fields.UNIQUE_VALUE) {
      return (UniqueValue)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'uniqueValue' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setUniqueValue(UniqueValue value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.UNIQUE_VALUE;
    value_ = value;
  }

  public ApplyDelta getApplyDelta() {
    if (getSetField() == _Fields.APPLY_DELTA) {
      return (ApplyDelta)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'applyDelta' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setApplyDelta(ApplyDelta value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.APPLY_DELTA;
    value_ = value;
  }

  public RequestValue getRequestValue() {
    if (getSetField() == _Fields.REQUEST_VALUE) {
      return (RequestValue)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'requestValue' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setRequestValue(RequestValue value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.REQUEST_VALUE;
    value_ = value;
  }

  public boolean isSetUniqueValue() {
    return setField_ == _Fields.UNIQUE_VALUE;
  }


  public boolean isSetApplyDelta() {
    return setField_ == _Fields.APPLY_DELTA;
  }


  public boolean isSetRequestValue() {
    return setField_ == _Fields.REQUEST_VALUE;
  }


  public boolean equals(Object other) {
    if (other instanceof RequestUnit) {
      return equals((RequestUnit)other);
    } else {
      return false;
    }
  }

  public boolean equals(RequestUnit other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(RequestUnit other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
