@ARSETTABLE @UPDATEWINS CREATE TABLE t1 (
@LWWINTEGER @SEMANTIC a int(10) unsigned NOT NULL,
@LWWINTEGER b int(10) unsigned AUTO_INCREMENT,
@LWWINTEGER @NOSEMANTIC c int(10) unsigned,
@LWWINTEGER d int(10) unsigned,
@LWWSTRING e varchar(50),
PRIMARY KEY (a)
) ENGINE=INNODB;

@ARSETTABLE @UPDATEWINS CREATE TABLE t2 (
@LWWINTEGER a int(10) unsigned NOT NULL,
@LWWINTEGER b int(10) unsigned,
@LWWINTEGER c int(10) unsigned,
@LWWINTEGER d int(10) unsigned,
@LWWSTRING e varchar(50),
PRIMARY KEY (a),
UNIQUE (b)
) ENGINE=INNODB;