@ARSETTABLE @UPDATEWINS CREATE TABLE t1 (
@LWWINTEGER @NOSEMANTIC a int(10) unsigned NOT NULL,
@LWWINTEGER b int(10) unsigned,
@LWWINTEGER c int(10) unsigned,
@LWWINTEGER d int(10) unsigned,
@LWWSTRING @NOSEMANTIC e varchar(50),
PRIMARY KEY (a)
) ENGINE=INNODB;

@ARSETTABLE @DELETEWINS CREATE TABLE t2 (
@LWWINTEGER a int(10) unsigned NOT NULL,
@LWWINTEGER b int(10) unsigned,
@LWWINTEGER c int(10) unsigned,
@LWWINTEGER d int(10) unsigned,
@LWWSTRING e varchar(50),
PRIMARY KEY (a),
@UPDATEWINS FOREIGN KEY (b) REFERENCES t1(b) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB;