JAVAC = javac
#TPCW_HOME=/victim5/JavaWebServer2.0
TPCW_HOME=/usr/WebSphere/AppServer
SERVLET_HOME=$(TPCW_HOME)/servlets
CLASS_HOME=$(TPCW_HOME)/classes
#Need to set you class path to:
#CLASSPATH=/victim5/JavaWebServer2.0/classes:/home/cain/JSDK2.0/lib/jsdk.jar

all: 	$(CLASS_HOME)/servlets.Address.class \
	$(CLASS_HOME)/servlets.Book.class \
	$(CLASS_HOME)/servlets.BuyConfirmResult.class \
	$(CLASS_HOME)/servlets.Cart.class \
	$(CLASS_HOME)/servlets.CartLine.class \
	$(CLASS_HOME)/servlets.Customer.class \
	$(CLASS_HOME)/servlets.Order.class \
	$(CLASS_HOME)/servlets.OrderLine.class \
	$(CLASS_HOME)/servlets.ShortBook.class \
	$(CLASS_HOME)/servlets.TPCW_Database.class \
	$(CLASS_HOME)/servlets.TPCW_promotional_processing.class \
	$(CLASS_HOME)/servlets.TPCW_say_hello.class \
	$(CLASS_HOME)/servlets.TPCW_Util.class \
	$(SERVLET_HOME)/servlets.TPCW_admin_request_servlet.class \
	$(SERVLET_HOME)/servlets.TPCW_admin_response_servlet.class \
	$(SERVLET_HOME)/servlets.TPCW_best_sellers_servlet.class \
	$(SERVLET_HOME)/servlets.TPCW_buy_confirm_servlet.class \
	$(SERVLET_HOME)/servlets.TPCW_buy_request_servlet.class \
	$(SERVLET_HOME)/servlets.TPCW_customer_registration_servlet.class \
	$(SERVLET_HOME)/servlets.TPCW_execute_search.class \
	$(SERVLET_HOME)/servlets.TPCW_home_interaction.class \
	$(SERVLET_HOME)/servlets.TPCW_new_products_servlet.class \
	$(SERVLET_HOME)/servlets.TPCW_new_products_servlet.class \
	$(SERVLET_HOME)/servlets.TPCW_order_inquiry_servlet.class \
	$(SERVLET_HOME)/servlets.TPCW_order_display_servlet.class \
	$(SERVLET_HOME)/servlets.TPCW_product_detail_servlet.class \
	$(SERVLET_HOME)/servlets.TPCW_search_request_servlet.class \
	$(SERVLET_HOME)/servlets.TPCW_shopping_cart_interaction.class

#stand alone classes
$(CLASS_HOME)/servlets.Address.class: servlets.Address.java
	$(JAVAC) -d $(CLASS_HOME) servlets.Address.java

$(CLASS_HOME)/servlets.Book.class: servlets.Book.java
	$(JAVAC) -d $(CLASS_HOME) servlets.Book.java

$(CLASS_HOME)/servlets.BuyConfirmResult.class: servlets.BuyConfirmResult.java
	$(JAVAC) -d $(CLASS_HOME) servlets.BuyConfirmResult.java

$(CLASS_HOME)/servlets.Cart.class: servlets.Cart.java
	$(JAVAC) -d $(CLASS_HOME) servlets.Cart.java

$(CLASS_HOME)/servlets.CartLine.class: servlets.CartLine.java
	$(JAVAC) -d $(CLASS_HOME) servlets.CartLine.java

$(CLASS_HOME)/servlets.Customer.class: servlets.Customer.java
	$(JAVAC) -d $(CLASS_HOME) servlets.Customer.java

$(CLASS_HOME)/servlets.Order.class: servlets.Order.java
	$(JAVAC) -d $(CLASS_HOME) servlets.Order.java

$(CLASS_HOME)/servlets.OrderLine.class: servlets.OrderLine.java
	$(JAVAC) -d $(CLASS_HOME) servlets.OrderLine.java

$(CLASS_HOME)/servlets.ShortBook.class: servlets.ShortBook.java
	$(JAVAC) -d $(CLASS_HOME) servlets.ShortBook.java

$(CLASS_HOME)/servlets.TPCW_Database.class: servlets.TPCW_Database.java
	$(JAVAC) -d $(CLASS_HOME) servlets.TPCW_Database.java

$(CLASS_HOME)/servlets.TPCW_promotional_processing.class: servlets.TPCW_promotional_processing.java
	$(JAVAC) -d $(CLASS_HOME) servlets.TPCW_promotional_processing.java

$(CLASS_HOME)/servlets.TPCW_say_hello.class: servlets.TPCW_say_hello.java
	$(JAVAC) -d $(CLASS_HOME) servlets.TPCW_say_hello.java

$(CLASS_HOME)/servlets.TPCW_Util.class: servlets.TPCW_Util.java
	$(JAVAC) -d $(CLASS_HOME) servlets.TPCW_Util.java

#servlets
$(SERVLET_HOME)/servlets.TPCW_admin_request_servlet.class: servlets.TPCW_admin_request_servlet.java
	$(JAVAC) -d $(SERVLET_HOME) servlets.TPCW_admin_request_servlet.java

$(SERVLET_HOME)/servlets.TPCW_admin_response_servlet.class: servlets.TPCW_admin_response_servlet.java
	$(JAVAC) -d $(SERVLET_HOME) servlets.TPCW_admin_response_servlet.java

$(SERVLET_HOME)/servlets.TPCW_best_sellers_servlet.class: servlets.TPCW_best_sellers_servlet.java
	$(JAVAC) -d $(SERVLET_HOME) servlets.TPCW_best_sellers_servlet.java

$(SERVLET_HOME)/servlets.TPCW_buy_confirm_servlet.class: servlets.TPCW_buy_confirm_servlet.java
	$(JAVAC) -d $(SERVLET_HOME) servlets.TPCW_buy_confirm_servlet.java

$(SERVLET_HOME)/servlets.TPCW_buy_request_servlet.class: servlets.TPCW_buy_request_servlet.java
	$(JAVAC) -d $(SERVLET_HOME) servlets.TPCW_buy_request_servlet.java

$(SERVLET_HOME)/servlets.TPCW_customer_registration_servlet.class: servlets.TPCW_customer_registration_servlet.java
	$(JAVAC) -d $(SERVLET_HOME) servlets.TPCW_customer_registration_servlet.java

$(SERVLET_HOME)/servlets.TPCW_execute_search.class: servlets.TPCW_execute_search.java
	$(JAVAC) -d $(SERVLET_HOME) servlets.TPCW_execute_search.java

$(SERVLET_HOME)/servlets.TPCW_home_interaction.class: servlets.TPCW_home_interaction.java
	$(JAVAC) -d $(SERVLET_HOME) servlets.TPCW_home_interaction.java

$(SERVLET_HOME)/servlets.TPCW_new_products_servlet.class: servlets.TPCW_new_products_servlet.java
	$(JAVAC) -d $(SERVLET_HOME) servlets.TPCW_new_products_servlet.java

$(SERVLET_HOME)/servlets.TPCW_order_display_servlet.class: servlets.TPCW_order_display_servlet.java
	$(JAVAC) -d $(SERVLET_HOME) servlets.TPCW_order_display_servlet.java

$(SERVLET_HOME)/servlets.TPCW_order_inquiry_servlet.class: servlets.TPCW_order_inquiry_servlet.java
	$(JAVAC) -d $(SERVLET_HOME) servlets.TPCW_order_inquiry_servlet.java

$(SERVLET_HOME)/servlets.TPCW_product_detail_servlet.class: servlets.TPCW_product_detail_servlet.java
	$(JAVAC) -d $(SERVLET_HOME) servlets.TPCW_product_detail_servlet.java

$(SERVLET_HOME)/servlets.TPCW_search_request_servlet.class: servlets.TPCW_search_request_servlet.java
	$(JAVAC) -d $(SERVLET_HOME) servlets.TPCW_search_request_servlet.java

$(SERVLET_HOME)/servlets.TPCW_shopping_cart_interaction.class: servlets.TPCW_shopping_cart_interaction.java
	$(JAVAC) -d $(SERVLET_HOME) servlets.TPCW_shopping_cart_interaction.java
